import manifestJson from "../data/imageManifest.json";

export interface ManifestEntry {
  width: number;
  height: number;
  widths: number[];
  avif: Record<string, string>;
  webp: Record<string, string>;
}

// imageManifest.json is generated by scripts/optimizeImages.mjs.
const manifest = manifestJson as Record<string, ManifestEntry>;

/**
 * Derive a manifest key from an image reference. Both `my-photo` and
 * `/my-photo.jpg` resolve to the key `my-photo`.
 *
 * Optimizer masters are flat-named (the key is the bare filename), so don't
 * reference optimized images with subdirectory paths — `/photos/my-photo.jpg`
 * would yield key `photos/my-photo` and never match the manifest.
 *
 * The extension is dropped, so `foo.svg` and `foo.png` collapse to the same key
 * `foo`. Optimizing a `foo.png` master would therefore also override a `foo.svg`
 * reference — keep distinct images on distinct basenames.
 */
export function toManifestKey(src: string): string {
  return src
    .replace(/^\//, "")
    .replace(/\.(avif|webp|jpe?g|png|gif|svg)$/i, "");
}

/** Variants for an optimized image, or undefined if the optimizer hasn't run for it. */
export function getImage(name: string): ManifestEntry | undefined {
  return manifest[name];
}
