import manifestJson from "../data/videoManifest.json";

export interface VideoEntry {
  width: number;
  height: number;
  mp4: string;
  webm: string;
  poster: string;
}

// videoManifest.json is generated by scripts/optimizeVideos.mjs.
const manifest = manifestJson as Record<string, VideoEntry>;

/** Optimized video for a manifest key, or undefined if the key isn't a video. */
export function getVideo(name: string): VideoEntry | undefined {
  return manifest[name];
}
